name: DEMO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  demo-job:
    runs-on: ubuntu-latezt

    steps:
      - name: Step 1 - Print message
        run: echo "Hello from GitHub Actions!"

      - name: Step 2 - Show current directory
        run: pwd

      - name: Step 3 - List files
        run: ls -la

      - name: step - Install flake8
        run: pip install flake8

      - name: Step 4 - Run flake8 (will fail if not installed)
        run: flake8 --version  


